# Comprehensive plant database for Homestead Tracker
# Based on Eliot Coleman and Nico Jabour's winter gardening techniques
# Expanded to include 60+ varieties for full homestead production

PLANT_DATABASE = [
    # ========== WINTER HARDY GREENS ==========
    {
        'id': 'spinach-1',
        'name': 'Spinach',
        'scientificName': 'Spinacia oleracea',
        'category': 'vegetable',
        'spacing': 4,
        'rowSpacing': 12,
        'daysToMaturity': 40,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': ['lettuce-1', 'radish-1', 'strawberry-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.5, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 35, 'max': 75},
        'soil_temp_min': 35,
        'transplantWeeksBefore': 6,
        'germination_days': 7,
        'ideal_seasons': ['spring', 'fall', 'winter'],
        'heat_tolerance': 'low',
        'icon': '🥬'
    },
    {
        'id': 'kale-1',
        'name': 'Kale (Lacinato)',
        'scientificName': 'Brassica oleracea',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 18,
        'daysToMaturity': 55,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': ['onion-1', 'beet-1', 'thyme-1'],
        'incompatiblePlants': ['tomato-1', 'bean-bush-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 40, 'max': 85},
        'soil_temp_min': 40,
        'transplantWeeksBefore': 6,

        'germination_days': 5,
        'ideal_seasons': ['spring', 'fall', 'winter'],
        'heat_tolerance': 'low',
        'icon': '🥬'
    },
    {
        'id': 'lettuce-1',
        'name': 'Lettuce (Mixed)',
        'scientificName': 'Lactuca sativa',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 45,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'radish-1', 'chives-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 40, 'max': 75},
        'soil_temp_min': 40,
        'transplantWeeksBefore': 4,
        
        'germination_days': 7,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'icon': '🥬'
    },
    # Lettuce type-specific entries for variety management
    {
        'id': 'lettuce-looseleaf-1',
        'name': 'Lettuce (Looseleaf)',
        'scientificName': 'Lactuca sativa',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 48,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'radish-1', 'chives-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 40, 'max': 75},
        'soil_temp_min': 40,
        'transplantWeeksBefore': 4,
        
        'germination_days': 7,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'icon': '🥬'
    },
    {
        'id': 'lettuce-romaine-1',
        'name': 'Lettuce (Romaine)',
        'scientificName': 'Lactuca sativa',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 68,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'radish-1', 'chives-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 40, 'max': 75},
        'soil_temp_min': 40,
        'transplantWeeksBefore': 4,
        
        'germination_days': 7,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'icon': '🥬'
    },
    {
        'id': 'lettuce-butterhead-1',
        'name': 'Lettuce (Butterhead)',
        'scientificName': 'Lactuca sativa',
        'category': 'vegetable',
        'spacing': 8,
        'rowSpacing': 12,
        'daysToMaturity': 60,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'radish-1', 'chives-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 40, 'max': 75},
        'soil_temp_min': 40,
        'transplantWeeksBefore': 4,
        
        'germination_days': 7,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'icon': '🥬'
    },
    {
        'id': 'lettuce-crisphead-1',
        'name': 'Lettuce (Crisphead)',
        'scientificName': 'Lactuca sativa',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 15,
        'daysToMaturity': 75,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['carrot-1', 'radish-1', 'chives-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 40, 'max': 75},
        'soil_temp_min': 40,
        'transplantWeeksBefore': 6,
        
        'germination_days': 8,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'icon': '🥬'
    },
    {
        'id': 'lettuce-summercrisp-1',
        'name': 'Lettuce (Summer Crisp)',
        'scientificName': 'Lactuca sativa',
        'category': 'vegetable',
        'spacing': 8,
        'rowSpacing': 12,
        'daysToMaturity': 55,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'radish-1', 'chives-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 40, 'max': 75},
        'soil_temp_min': 40,
        'transplantWeeksBefore': 4,
        
        'germination_days': 7,
        'ideal_seasons': ['spring', 'summer', 'fall'],
        'heat_tolerance': 'medium',
        'icon': '🥬'
    },
    {
        'id': 'arugula-1',
        'name': 'Arugula',
        'scientificName': 'Eruca vesicaria',
        'category': 'vegetable',
        'spacing': 4,
        'rowSpacing': 12,
        'daysToMaturity': 30,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['lettuce-1', 'spinach-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 40, 'max': 70},
        'soil_temp_min': 40,
        'transplantWeeksBefore': 4,
        
        'germination_days': 5,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'icon': '🥬'
    },
    {
        'id': 'chard-1',
        'name': 'Swiss Chard',
        'scientificName': 'Beta vulgaris',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 18,
        'daysToMaturity': 50,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['onion-1', 'beet-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 50, 'max': 85},
        'soil_temp_min': 50,
        'transplantWeeksBefore': 4,
        
        'germination_days': 7,
        'ideal_seasons': ['spring', 'summer', 'fall'],
        'heat_tolerance': 'medium',
        'icon': '🥬'
    },

    # ========== ROOT VEGETABLES ==========
    {
        'id': 'carrot-1',
        'name': 'Carrot',
        'scientificName': 'Daucus carota',
        'category': 'vegetable',
        'spacing': 3,
        'rowSpacing': 12,
        'daysToMaturity': 70,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['onion-1', 'lettuce-1', 'rosemary-1'],
        'incompatiblePlants': ['dill-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.8},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 45, 'max': 85},
        'soil_temp_min': 45,
        'transplantWeeksBefore': 0,
        
        'germination_days': 10,
        'ideal_seasons': ['spring', 'summer', 'fall'],
        'heat_tolerance': 'medium',
        'icon': '🥕'
    },
    {
        'id': 'beet-1',
        'name': 'Beet',
        'scientificName': 'Beta vulgaris',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 55,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['onion-1', 'kale-1', 'lettuce-1'],
        'incompatiblePlants': ['bean-pole-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 50, 'max': 85},
        'soil_temp_min': 50,
        'transplantWeeksBefore': 4,
        
        'germination_days': 7,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'medium',
        'icon': '🥕'
    },
    {
        'id': 'radish-1',
        'name': 'Radish',
        'scientificName': 'Raphanus sativus',
        'category': 'vegetable',
        'spacing': 1,
        'rowSpacing': 4,
        'daysToMaturity': 25,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['lettuce-1', 'spinach-1', 'nasturtium-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 45, 'max': 85},
        'soil_temp_min': 45,
        'transplantWeeksBefore': 0,
        
        'germination_days': 4,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'icon': '🥕'
    },
    {
        'id': 'potato-1',
        'name': 'Potato',
        'scientificName': 'Solanum tuberosum',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 30,
        'daysToMaturity': 90,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['bean-bush-1', 'horseradish-1'],
        'incompatiblePlants': ['tomato-1', 'squash-summer-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.0, 'max': 6.0},
        'plantingDepth': 4,
        'germinationTemp': {'min': 45, 'max': 55},
        'soil_temp_min': 45,
        'transplantWeeksBefore': 2,
        
        'germination_days': 14,
        'ideal_seasons': ['spring', 'summer'],
        'heat_tolerance': 'medium',
        'icon': '🥔'
    },

    # ========== BRASSICAS (COLE CROPS) ==========
    {
        'id': 'broccoli-1',
        'name': 'Broccoli',
        'scientificName': 'Brassica oleracea',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 24,
        'daysToMaturity': 65,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['onion-1', 'sage-1', 'thyme-1'],
        'incompatiblePlants': ['tomato-1', 'strawberry-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 45, 'max': 85},
        'soil_temp_min': 45,
        'transplantWeeksBefore': 4,
        
        'germination_days': 5,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'icon': '🥦'
    },
    {
        'id': 'cauliflower-1',
        'name': 'Cauliflower',
        'scientificName': 'Brassica oleracea',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 24,
        'daysToMaturity': 75,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['onion-1', 'sage-1'],
        'incompatiblePlants': ['tomato-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.5, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 45, 'max': 85},
        'soil_temp_min': 45,
        'transplantWeeksBefore': 4,
        
        'germination_days': 5,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'icon': '🥦'
    },
    {
        'id': 'cabbage-1',
        'name': 'Cabbage',
        'scientificName': 'Brassica oleracea',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 24,
        'daysToMaturity': 70,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['onion-1', 'thyme-1'],
        'incompatiblePlants': ['tomato-1', 'bean-pole-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.5, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 45, 'max': 85},
        'soil_temp_min': 45,
        'transplantWeeksBefore': 4,
        
        'germination_days': 5,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'icon': '🥬'
    },

    # ========== BEANS & PEAS ==========
    {
        'id': 'bean-bush-1',
        'name': 'Bean (Bush)',
        'scientificName': 'Phaseolus vulgaris',
        'category': 'vegetable',
        'spacing': 4,
        'rowSpacing': 18,
        'daysToMaturity': 55,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['carrot-1', 'cucumber-1', 'potato-1', 'marigold-1'],
        'incompatiblePlants': ['onion-1', 'garlic-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 60, 'max': 85},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        
        'germination_days': 7,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'high',
        'icon': '🫘'
    },
    {
        'id': 'bean-pole-1',
        'name': 'Bean (Pole)',
        'scientificName': 'Phaseolus vulgaris',
        'category': 'vegetable',
        'spacing': 4,
        'rowSpacing': 24,
        'daysToMaturity': 65,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['carrot-1', 'cucumber-1', 'sunflower-1'],
        'incompatiblePlants': ['onion-1', 'beet-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 60, 'max': 85},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        
        'germination_days': 7,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'high',
        'icon': '🫘'
    },
    {
        'id': 'pea-1',
        'name': 'Pea (Shelling)',
        'scientificName': 'Pisum sativum',
        'category': 'vegetable',
        'spacing': 4,
        'rowSpacing': 24,
        'daysToMaturity': 60,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['carrot-1', 'radish-1', 'cucumber-1'],
        'incompatiblePlants': ['onion-1', 'garlic-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 1,
        'germinationTemp': {'min': 40, 'max': 75},
        'soil_temp_min': 40,
        'transplantWeeksBefore': 6,
        
        'germination_days': 7,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'icon': '🫘'
    },

    # ========== SUMMER CROPS (TOMATOES, PEPPERS, EGGPLANT) ==========
    {
        'id': 'tomato-1',
        'name': 'Tomato (Beefsteak)',
        'scientificName': 'Solanum lycopersicum',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 36,
        'daysToMaturity': 80,
        'frostTolerance': 'very-tender',
        'winterHardy': False,
        'companionPlants': ['basil-1', 'carrot-1', 'parsley-1', 'marigold-1'],
        'incompatiblePlants': ['kale-1', 'potato-1', 'fennel-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.8},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 60, 'max': 85},
        'soil_temp_min': 60,
        'transplantWeeksBefore': -2,
        
        'germination_days': 7,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'high',
        'icon': '🍅'
    },
    {
        'id': 'tomato-cherry-1',
        'name': 'Tomato (Cherry)',
        'scientificName': 'Solanum lycopersicum',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 36,
        'daysToMaturity': 60,
        'frostTolerance': 'very-tender',
        'winterHardy': False,
        'companionPlants': ['basil-1', 'nasturtium-1'],
        'incompatiblePlants': ['kale-1', 'potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.8},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 60, 'max': 85},
        'soil_temp_min': 60,
        'transplantWeeksBefore': -2,
        
        'germination_days': 7,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'high',
        'icon': '🍅'
    },
    {
        'id': 'pepper-bell-1',
        'name': 'Pepper (Bell)',
        'scientificName': 'Capsicum annuum',
        'category': 'vegetable',
        'spacing': 18,
        'rowSpacing': 24,
        'daysToMaturity': 75,
        'frostTolerance': 'very-tender',
        'winterHardy': False,
        'companionPlants': ['basil-1', 'onion-1', 'oregano-1'],
        'incompatiblePlants': ['fennel-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.8},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 65, 'max': 85},
        'soil_temp_min': 65,
        'transplantWeeksBefore': -2,
        
        'germination_days': 10,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'high',
        'icon': '🌶️'
    },
    {
        'id': 'pepper-hot-1',
        'name': 'Pepper (Hot/Jalapeño)',
        'scientificName': 'Capsicum annuum',
        'category': 'vegetable',
        'spacing': 18,
        'rowSpacing': 24,
        'daysToMaturity': 70,
        'frostTolerance': 'very-tender',
        'winterHardy': False,
        'companionPlants': ['basil-1', 'oregano-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.8},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 65, 'max': 85},
        'soil_temp_min': 65,
        'transplantWeeksBefore': -2,
        
        'germination_days': 10,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'excellent',
        'icon': '🌶️'
    },

    # ========== SQUASH, CUCUMBERS, MELONS ==========
    {
        'id': 'squash-summer-1',
        'name': 'Squash (Summer/Zucchini)',
        'scientificName': 'Cucurbita pepo',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 36,
        'daysToMaturity': 50,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['bean-bush-1', 'nasturtium-1', 'marigold-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 60, 'max': 95},
        'soil_temp_min': 60,
        'transplantWeeksBefore': -1,
        
        'germination_days': 6,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'high',
        'icon': '🥒'
    },
    {
        'id': 'squash-winter-1',
        'name': 'Squash (Winter/Butternut)',
        'scientificName': 'Cucurbita moschata',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 60,
        'daysToMaturity': 95,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['bean-bush-1', 'nasturtium-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 60, 'max': 95},
        'soil_temp_min': 60,
        'transplantWeeksBefore': -1,
        
        'germination_days': 7,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'high',
        'icon': '🎃'
    },
    {
        'id': 'cucumber-1',
        'name': 'Cucumber',
        'scientificName': 'Cucumis sativus',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 60,
        'daysToMaturity': 55,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['bean-bush-1', 'pea-1', 'radish-1', 'dill-1'],
        'incompatiblePlants': ['potato-1', 'sage-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 60, 'max': 95},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        
        'germination_days': 6,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'high',
        'icon': '🥒'
    },
    {
        'id': 'melon-1',
        'name': 'Melon (Cantaloupe)',
        'scientificName': 'Cucumis melo',
        'category': 'vegetable',
        'spacing': 17,
        'rowSpacing': 60,
        'daysToMaturity': 85,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['nasturtium-1', 'marigold-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.5},
        'plantingDepth': 1,
        'germinationTemp': {'min': 70, 'max': 95},
        'soil_temp_min': 70,
        'transplantWeeksBefore': -1,
        
        'germination_days': 7,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'excellent',
        'icon': '🍈'
    },
    {
        'id': 'watermelon-1',
        'name': 'Watermelon',
        'scientificName': 'Citrullus lanatus',
        'category': 'vegetable',
        'spacing': 17,
        'rowSpacing': 72,
        'daysToMaturity': 90,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['nasturtium-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.8},
        'plantingDepth': 1,
        'germinationTemp': {'min': 70, 'max': 95},
        'soil_temp_min': 70,
        'transplantWeeksBefore': -2,
        
        'germination_days': 7,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'excellent',
        'icon': '🍉'
    },

    # ========== ALLIUMS (ONIONS, GARLIC, LEEKS) ==========
    {
        'id': 'onion-1',
        'name': 'Onion (Storage)',
        'scientificName': 'Allium cepa',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 110,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'beet-1', 'lettuce-1'],
        'incompatiblePlants': ['bean-bush-1', 'pea-1', 'sage-1'],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 50, 'max': 95},
        'soil_temp_min': 50,
        'transplantWeeksBefore': 8,
        
        'germination_days': 7,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'medium',
        'icon': '🧅'
    },
    {
        'id': 'garlic-1',
        'name': 'Garlic',
        'scientificName': 'Allium sativum',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 240,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['tomato-1', 'rose-1'],
        'incompatiblePlants': ['bean-bush-1', 'pea-1'],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 2,
        'germinationTemp': {'min': 32, 'max': 50},
        'soil_temp_min': 32,
        'transplantWeeksBefore': 0,
        
        'germination_days': 7,
        'ideal_seasons': ['fall'],
        'heat_tolerance': 'medium',
        'icon': '🧄'
    },
    {
        'id': 'leek-1',
        'name': 'Leek',
        'scientificName': 'Allium ampeloprasum',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 120,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'onion-1'],
        'incompatiblePlants': ['bean-bush-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 45, 'max': 85},
        'soil_temp_min': 45,
        'transplantWeeksBefore': 8,
        
        'germination_days': 10,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'icon': '🧅'
    },
    {
        'id': 'chives-1',
        'name': 'Chives',
        'scientificName': 'Allium schoenoprasum',
        'category': 'herb',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 60,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'tomato-1', 'rose-1'],
        'incompatiblePlants': ['bean-bush-1', 'pea-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 6,
        
        'germination_days': 10,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'medium',
        'icon': '🌿'
    },

    # ========== CULINARY HERBS ==========
    {
        'id': 'basil-1',
        'name': 'Basil (Sweet)',
        'scientificName': 'Ocimum basilicum',
        'category': 'herb',
        'spacing': 7,
        'rowSpacing': 12,
        'daysToMaturity': 60,
        'frostTolerance': 'very-tender',
        'winterHardy': False,
        'companionPlants': ['tomato-1', 'pepper-bell-1', 'oregano-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 70, 'max': 85},
        'soil_temp_min': 70,
        'transplantWeeksBefore': -1,
        
        'germination_days': 7,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'excellent',
        'icon': '🌿'
    },
    {
        'id': 'parsley-1',
        'name': 'Parsley',
        'scientificName': 'Petroselinum crispum',
        'category': 'herb',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 70,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['tomato-1', 'asparagus-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 50, 'max': 80},
        'soil_temp_min': 50,
        'transplantWeeksBefore': 4,
        
        'germination_days': 14,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'medium',
        'icon': '🌿'
    },
    {
        'id': 'cilantro-1',
        'name': 'Cilantro/Coriander',
        'scientificName': 'Coriandrum sativum',
        'category': 'herb',
        'spacing': 12,
        'rowSpacing': 12,
        'daysToMaturity': 45,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['tomato-1', 'anise-1'],
        'incompatiblePlants': ['fennel-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.2, 'max': 6.8},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 55, 'max': 68},
        'soil_temp_min': 55,
        'transplantWeeksBefore': 2,
        
        'germination_days': 7,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'icon': '🌿'
    },
    {
        'id': 'dill-1',
        'name': 'Dill',
        'scientificName': 'Anethum graveolens',
        'category': 'herb',
        'spacing': 8,
        'rowSpacing': 12,
        'daysToMaturity': 50,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['cucumber-1', 'lettuce-1', 'onion-1'],
        'incompatiblePlants': ['carrot-1', 'tomato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 6.5},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        
        'germination_days': 10,
        'ideal_seasons': ['spring', 'summer'],
        'heat_tolerance': 'medium',
        'icon': '🌿'
    },
    {
        'id': 'oregano-1',
        'name': 'Oregano',
        'scientificName': 'Origanum vulgare',
        'category': 'herb',
        'spacing': 12,
        'rowSpacing': 18,
        'daysToMaturity': 80,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['pepper-bell-1', 'tomato-1', 'basil-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 8.0},
        'plantingDepth': 0.125,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 6,
        
        'germination_days': 10,
        'ideal_seasons': ['spring', 'summer'],
        'heat_tolerance': 'high',
        'icon': '🌿'
    },
    {
        'id': 'thyme-1',
        'name': 'Thyme',
        'scientificName': 'Thymus vulgaris',
        'category': 'herb',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 90,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['cabbage-1', 'tomato-1', 'strawberry-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 8.0},
        'plantingDepth': 0.125,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 8,
        
        'germination_days': 14,
        'ideal_seasons': ['spring', 'summer'],
        'heat_tolerance': 'high',
        'icon': '🌿'
    },
    {
        'id': 'sage-1',
        'name': 'Sage',
        'scientificName': 'Salvia officinalis',
        'category': 'herb',
        'spacing': 12,
        'rowSpacing': 24,
        'daysToMaturity': 75,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'cabbage-1', 'strawberry-1'],
        'incompatiblePlants': ['cucumber-1', 'onion-1'],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.125,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 6,
        
        'germination_days': 14,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'high',
        'icon': '🌿'
    },
    {
        'id': 'rosemary-1',
        'name': 'Rosemary',
        'scientificName': 'Rosmarinus officinalis',
        'category': 'herb',
        'spacing': 12,
        'rowSpacing': 24,
        'daysToMaturity': 90,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['carrot-1', 'cabbage-1', 'sage-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.125,
        'germinationTemp': {'min': 65, 'max': 70},
        'soil_temp_min': 65,
        'transplantWeeksBefore': 8,
        
        'germination_days': 21,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'high',
        'icon': '🌿'
    },
    {
        'id': 'mint-1',
        'name': 'Mint (Spearmint)',
        'scientificName': 'Mentha spicata',
        'category': 'herb',
        'spacing': 8,
        'rowSpacing': 24,
        'daysToMaturity': 60,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['cabbage-1', 'tomato-1'],
        'incompatiblePlants': ['parsley-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 65, 'max': 70},
        'soil_temp_min': 65,
        'transplantWeeksBefore': 6,
        
        'germination_days': 10,
        'ideal_seasons': ['spring', 'summer'],
        'heat_tolerance': 'medium',
        'icon': '🌿'
    },

    # ========== COMPANION FLOWERS ==========
    {
        'id': 'marigold-1',
        'name': 'Marigold (French)',
        'scientificName': 'Tagetes patula',
        'category': 'flower',
        'spacing': 10,
        'rowSpacing': 12,
        'daysToMaturity': 50,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['tomato-1', 'bean-bush-1', 'squash-summer-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 70, 'max': 75},
        'soil_temp_min': 70,
        'transplantWeeksBefore': 0,
        'notes': 'Repels nematodes, aphids, and whiteflies. Attracts pollinators.',
        'icon': '🌼'
    },
    {
        'id': 'nasturtium-1',
        'name': 'Nasturtium',
        'scientificName': 'Tropaeolum majus',
        'category': 'flower',
        'spacing': 12,
        'rowSpacing': 12,
        'daysToMaturity': 50,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['cucumber-1', 'radish-1', 'squash-summer-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 8.0},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 65, 'max': 70},
        'soil_temp_min': 65,
        'transplantWeeksBefore': -1,
        'notes': 'Edible flowers and leaves. Trap crop for aphids. Repels squash bugs.',
        'icon': '🌺'
    },
    {
        'id': 'sunflower-1',
        'name': 'Sunflower',
        'scientificName': 'Helianthus annuus',
        'category': 'flower',
        'spacing': 24,
        'rowSpacing': 30,
        'daysToMaturity': 80,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['bean-pole-1', 'cucumber-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 1,
        'germinationTemp': {'min': 70, 'max': 85},
        'soil_temp_min': 70,
        'transplantWeeksBefore': -1,
        'notes': 'Attracts birds and pollinators. Can provide shade and trellis.',
        'icon': '🌻'
    },
    {
        'id': 'zinnia-1',
        'name': 'Zinnia',
        'scientificName': 'Zinnia elegans',
        'category': 'flower',
        'spacing': 12,
        'rowSpacing': 18,
        'daysToMaturity': 60,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': [],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 7.5},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 70, 'max': 80},
        'soil_temp_min': 70,
        'transplantWeeksBefore': -1,
        'notes': 'Attracts butterflies and beneficial insects. Great cut flower.',
        'icon': '🌸'
    },
    {
        'id': 'calendula-1',
        'name': 'Calendula (Pot Marigold)',
        'scientificName': 'Calendula officinalis',
        'category': 'flower',
        'spacing': 12,
        'rowSpacing': 12,
        'daysToMaturity': 50,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['tomato-1', 'lettuce-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 2,
        'notes': 'Edible and medicinal. Attracts beneficial insects. Repels aphids.',
        'icon': '🌼'
    },
    {
        'id': 'borage-1',
        'name': 'Borage',
        'scientificName': 'Borago officinalis',
        'category': 'flower',
        'spacing': 18,
        'rowSpacing': 18,
        'daysToMaturity': 55,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['tomato-1', 'squash-summer-1', 'strawberry-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'notes': 'Attracts bees. Edible flowers. Deters tomato hornworms.',
        'icon': '🌺'
    },

    # ========== BERRIES & FRUITS ==========
    {
        'id': 'strawberry-1',
        'name': 'Strawberry',
        'scientificName': 'Fragaria × ananassa',
        'category': 'fruit',
        'spacing': 12,
        'rowSpacing': 24,
        'daysToMaturity': 90,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['spinach-1', 'lettuce-1', 'thyme-1', 'borage-1'],
        'incompatiblePlants': ['cabbage-1', 'broccoli-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 6.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 75},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        
        'germination_days': 21,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'medium',
        'icon': '🍓'
    },
    {
        'id': 'raspberry-1',
        'name': 'Raspberry',
        'scientificName': 'Rubus idaeus',
        'category': 'fruit',
        'spacing': 24,
        'rowSpacing': 72,
        'daysToMaturity': 365,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': ['garlic-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 6.5},
        'plantingDepth': 3,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'notes': 'Perennial. Fruits on second-year canes. Needs support.',
        'icon': '🫐'
    },
    {
        'id': 'blueberry-1',
        'name': 'Blueberry',
        'scientificName': 'Vaccinium corymbosum',
        'category': 'fruit',
        'spacing': 48,
        'rowSpacing': 72,
        'daysToMaturity': 730,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': [],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 4.5, 'max': 5.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'notes': 'Perennial shrub. Needs acidic soil. Plant 2+ varieties for pollination.',
        'icon': '🫐'
    },
    {
        'id': 'corn-1',
        'name': 'Corn',
        'scientificName': 'Zea mays',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 36,
        'daysToMaturity': 75,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['bean-1', 'squash-1', 'cucumber-1', 'pea-1'],
        'incompatiblePlants': ['tomato-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.8, 'max': 7.0},
        'plantingDepth': 1.5,
        'germinationTemp': {'min': 60, 'max': 95},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'germination_days': 7,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'high',
        'notes': 'Plant in blocks for better pollination. Needs warm soil. Part of "Three Sisters" planting.',
        'icon': '🌽'
    },
    {
        'id': 'asparagus-1',
        'name': 'Asparagus',
        'scientificName': 'Asparagus officinalis',
        'category': 'vegetable',
        'spacing': 18,
        'rowSpacing': 60,
        'daysToMaturity': 730,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': ['tomato-1', 'parsley-1', 'basil-1', 'nasturtium-1'],
        'incompatiblePlants': ['onion-1', 'garlic-1', 'potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.5, 'max': 7.5},
        'plantingDepth': 6,
        'germinationTemp': {'min': 60, 'max': 85},
        'soil_temp_min': 50,
        'transplantWeeksBefore': 0,
        'germination_days': 21,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'medium',
        'notes': 'Perennial crop. Plant crowns 6" deep. First light harvest year 2, full harvest year 3+. Productive for 15-20 years. Harvest spears when 6-8" tall for 6-8 weeks in spring.',
        'icon': '🥒'
    },
    {
        'id': 'brussels-sprouts-1',
        'name': 'Brussels Sprouts',
        'scientificName': 'Brassica oleracea var. gemmifera',
        'category': 'vegetable',
        'spacing': 18,
        'rowSpacing': 30,
        'daysToMaturity': 100,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': ['onion-1', 'sage-1', 'thyme-1', 'beet-1'],
        'incompatiblePlants': ['tomato-1', 'strawberry-1', 'bean-pole-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 45, 'max': 85},
        'soil_temp_min': 45,
        'transplantWeeksBefore': 4,
        'germination_days': 5,
        'ideal_seasons': ['fall', 'winter'],
        'heat_tolerance': 'low',
        'notes': 'Flavor improves after frost. Start indoors 4 weeks before last frost for fall harvest. Remove lower leaves as sprouts develop. Harvest from bottom up when sprouts are 1-2" diameter.',
        'icon': '🥬'
    },
    {
        'id': 'eggplant-1',
        'name': 'Eggplant',
        'scientificName': 'Solanum melongena',
        'category': 'vegetable',
        'spacing': 18,
        'rowSpacing': 30,
        'daysToMaturity': 70,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['bean-bush-1', 'pepper-bell-1', 'thyme-1', 'marigold-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 70, 'max': 90},
        'soil_temp_min': 70,
        'transplantWeeksBefore': -2,
        'germination_days': 10,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'high',
        'notes': 'Requires warm soil (70°F+). Start indoors 8-10 weeks before last frost. Harvest when skin is glossy and firm. Support heavy fruiting plants with stakes.',
        'icon': '🍆'
    },
    {
        'id': 'celery-1',
        'name': 'Celery',
        'scientificName': 'Apium graveolens',
        'category': 'vegetable',
        'spacing': 8,
        'rowSpacing': 12,
        'daysToMaturity': 85,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['onion-1', 'leek-1', 'cabbage-1', 'tomato-1'],
        'incompatiblePlants': ['potato-1', 'carrot-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0.125,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 55,
        'transplantWeeksBefore': 10,
        'germination_days': 14,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'notes': 'Requires consistent moisture. Start indoors 10-12 weeks before last frost. Soak seeds 24 hours before planting. Blanch stalks 2 weeks before harvest for milder flavor.',
        'icon': '🥬'
    },
    {
        'id': 'shallot-1',
        'name': 'Shallot',
        'scientificName': 'Allium cepa var. aggregatum',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 90,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['carrot-1', 'beet-1', 'lettuce-1', 'strawberry-1'],
        'incompatiblePlants': ['bean-bush-1', 'bean-pole-1', 'pea-1', 'sage-1'],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 50, 'max': 85},
        'soil_temp_min': 45,
        'transplantWeeksBefore': 0,
        'germination_days': 7,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'medium',
        'notes': 'Plant sets in early spring or fall. Each bulb divides into 4-8 new bulbs. Harvest when tops fall over. Cure in warm, dry location for 2-3 weeks before storage.',
        'icon': '🧅'
    },
    {
        'id': 'turnip-1',
        'name': 'Turnip',
        'scientificName': 'Brassica rapa',
        'category': 'vegetable',
        'spacing': 4,
        'rowSpacing': 12,
        'daysToMaturity': 50,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['pea-1', 'bean-bush-1', 'nasturtium-1'],
        'incompatiblePlants': ['potato-1', 'kale-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 40, 'max': 85},
        'soil_temp_min': 40,
        'transplantWeeksBefore': 0,
        'germination_days': 5,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'notes': 'Direct seed only - does not transplant well. Thin to 4" spacing when 2" tall. Harvest roots when 2-3" diameter. Greens are also edible. Flavor sweetens after frost.',
        'icon': '🥕'
    },
    {
        'id': 'collard-greens-1',
        'name': 'Collard Greens',
        'scientificName': 'Brassica oleracea var. viridis',
        'category': 'vegetable',
        'spacing': 18,
        'rowSpacing': 24,
        'daysToMaturity': 60,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': ['onion-1', 'beet-1', 'thyme-1', 'sage-1'],
        'incompatiblePlants': ['tomato-1', 'bean-bush-1', 'strawberry-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 45, 'max': 85},
        'soil_temp_min': 45,
        'transplantWeeksBefore': 4,
        'germination_days': 5,
        'ideal_seasons': ['spring', 'fall', 'winter'],
        'heat_tolerance': 'medium',
        'notes': 'Extremely cold hardy - tolerates temperatures to 10°F. Flavor improves after frost. Harvest lower leaves continuously. Can overwinter in mild climates for early spring harvest.',
        'icon': '🥬'
    },
    {
        'id': 'okra-1',
        'name': 'Okra',
        'scientificName': 'Abelmoschus esculentus',
        'category': 'vegetable',
        'spacing': 12,
        'rowSpacing': 36,
        'daysToMaturity': 55,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['pepper-bell-1', 'eggplant-1', 'cucumber-1', 'melon-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 1,
        'germinationTemp': {'min': 70, 'max': 95},
        'soil_temp_min': 70,
        'transplantWeeksBefore': -2,
        'germination_days': 7,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'high',
        'notes': 'Thrives in hot weather. Soak seeds 12-24 hours before planting. Harvest pods when 2-4" long (daily picking increases production). Plants can grow 4-6 feet tall.',
        'icon': '🌶️'
    },
    {
        'id': 'kohlrabi-1',
        'name': 'Kohlrabi',
        'scientificName': 'Brassica oleracea var. gongylodes',
        'category': 'vegetable',
        'spacing': 6,
        'rowSpacing': 12,
        'daysToMaturity': 50,
        'frostTolerance': 'hardy',
        'winterHardy': False,
        'companionPlants': ['onion-1', 'beet-1', 'cucumber-1'],
        'incompatiblePlants': ['tomato-1', 'bean-pole-1', 'strawberry-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0.5,
        'germinationTemp': {'min': 45, 'max': 85},
        'soil_temp_min': 45,
        'transplantWeeksBefore': 4,
        'germination_days': 5,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'notes': 'Harvest when bulbs are 2-3" diameter for best flavor. Can tolerate light frosts. Fast-growing cool season crop. Both bulb and leaves are edible.',
        'icon': '🥬'
    },
    {
        'id': 'pumpkin-1',
        'name': 'Pumpkin',
        'scientificName': 'Cucurbita pepo',
        'category': 'vegetable',
        'spacing': 24,
        'rowSpacing': 72,
        'daysToMaturity': 100,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['bean-bush-1', 'corn-1', 'nasturtium-1', 'marigold-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 1,
        'germinationTemp': {'min': 65, 'max': 95},
        'soil_temp_min': 65,
        'transplantWeeksBefore': -1,
        'germination_days': 7,
        'ideal_seasons': ['summer'],
        'heat_tolerance': 'high',
        'notes': 'Requires large space - vines can spread 15-20 feet. Part of "Three Sisters" planting. Harvest when skin is hard and cannot be punctured with fingernail. Cure 10-14 days before storage.',
        'icon': '🎃'
    },
    {
        'id': 'blackberry-1',
        'name': 'Blackberry',
        'scientificName': 'Rubus fruticosus',
        'category': 'fruit',
        'spacing': 36,
        'rowSpacing': 96,
        'daysToMaturity': 365,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['nasturtium-1', 'marigold-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 7.0},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 75},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'germination_days': 21,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'medium',
        'notes': 'Perennial cane fruit. First harvest year 2. Very productive - can yield 10-20 lbs per plant. Fruits on second-year canes. Requires support/trellis. Can be invasive - plant with root barriers.',
        'icon': '🫐'
    },
    {
        'id': 'grape-1',
        'name': 'Grape',
        'scientificName': 'Vitis vinifera',
        'category': 'fruit',
        'spacing': 96,
        'rowSpacing': 96,
        'daysToMaturity': 1095,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['basil-1', 'oregano-1', 'bean-bush-1'],
        'incompatiblePlants': ['cabbage-1', 'radish-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 7.0},
        'plantingDepth': 0,
        'germinationTemp': {'min': 70, 'max': 80},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'germination_days': 30,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'high',
        'notes': 'Perennial vine. First harvest year 3. Versatile - fresh eating, juice, wine, raisins. Requires sturdy support structure. Prune annually in late winter. Can be productive for 50+ years.',
        'icon': '🍇'
    },
    {
        'id': 'currant-1',
        'name': 'Currant',
        'scientificName': 'Ribes rubrum',
        'category': 'fruit',
        'spacing': 48,
        'rowSpacing': 72,
        'daysToMaturity': 730,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': ['nasturtium-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'partial',
        'soilPH': {'min': 5.5, 'max': 7.0},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 50,
        'transplantWeeksBefore': 0,
        'germination_days': 30,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'notes': 'Perennial shrub. First harvest year 2-3. Red and black varieties available. Tolerates partial shade. High in vitamin C. Productive for 15-20 years. Note: White pine blister rust host in some areas.',
        'icon': '🫐'
    },
    {
        'id': 'gooseberry-1',
        'name': 'Gooseberry',
        'scientificName': 'Ribes uva-crispa',
        'category': 'fruit',
        'spacing': 48,
        'rowSpacing': 72,
        'daysToMaturity': 730,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': ['nasturtium-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 6.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 50,
        'transplantWeeksBefore': 0,
        'germination_days': 30,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'notes': 'Perennial shrub. First harvest year 2-3. Green, red, or yellow varieties. Tolerates partial shade. Thorny canes on most varieties. Very cold hardy. Productive for 15-20 years.',
        'icon': '🫐'
    },
    {
        'id': 'elderberry-1',
        'name': 'Elderberry',
        'scientificName': 'Sambucus nigra',
        'category': 'fruit',
        'spacing': 72,
        'rowSpacing': 120,
        'daysToMaturity': 730,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': [],
        'incompatiblePlants': [],
        'waterNeeds': 'high',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 6.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 75},
        'soil_temp_min': 55,
        'transplantWeeksBefore': 0,
        'germination_days': 60,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'medium',
        'notes': 'Perennial shrub. First harvest year 2-3. Medicinal value - immune support, antiviral. Plant 2+ varieties for pollination. Flowers and berries edible (cook berries first). Grows 6-12 feet tall. Productive for 30+ years.',
        'icon': '🫐'
    },
    {
        'id': 'fennel-1',
        'name': 'Fennel',
        'scientificName': 'Foeniculum vulgare',
        'category': 'herb',
        'spacing': 12,
        'rowSpacing': 18,
        'daysToMaturity': 65,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['pea-1', 'cucumber-1', 'lettuce-1'],
        'incompatiblePlants': ['tomato-1', 'bean-bush-1', 'bean-pole-1', 'cilantro-1', 'dill-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 7.0},
        'plantingDepth': 0.25,
        'germinationTemp': {'min': 50, 'max': 70},
        'soil_temp_min': 50,
        'transplantWeeksBefore': 4,
        'germination_days': 10,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'low',
        'notes': 'Dual-use: herb (fronds, seeds) and vegetable (Florence bulbing types). Perennial zones 6-10. ALLELOPATHIC - isolate from most plants. Attracts beneficial insects. Bolts in heat. All parts edible: bulb, fronds, seeds, pollen.',
        'icon': '🌿'
    },
    {
        'id': 'lavender-1',
        'name': 'Lavender (English)',
        'scientificName': 'Lavandula angustifolia',
        'category': 'herb',
        'spacing': 18,
        'rowSpacing': 24,
        'daysToMaturity': 90,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['rosemary-1', 'sage-1', 'thyme-1', 'oregano-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.5, 'max': 8.0},
        'plantingDepth': 0.125,
        'germinationTemp': {'min': 65, 'max': 70},
        'soil_temp_min': 65,
        'transplantWeeksBefore': 10,
        'germination_days': 21,
        'ideal_seasons': ['spring', 'summer'],
        'heat_tolerance': 'high',
        'notes': 'Perennial zones 5-9, productive 10-15 years. Requires excellent drainage - will rot in wet soil. Prefers alkaline soil. Drought-tolerant once established. Medicinal: anxiety, sleep, pain relief. Slow germination. 2-3 harvests per season.',
        'icon': '🌿'
    },
    {
        'id': 'lemon-balm-1',
        'name': 'Lemon Balm',
        'scientificName': 'Melissa officinalis',
        'category': 'herb',
        'spacing': 18,
        'rowSpacing': 24,
        'daysToMaturity': 70,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['tomato-1', 'squash-summer-1', 'broccoli-1', 'cauliflower-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'partial',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0.125,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 6,
        'germination_days': 14,
        'ideal_seasons': ['spring', 'summer'],
        'heat_tolerance': 'medium',
        'notes': 'Perennial zones 4-9. WARNING: Very aggressive spreader - can become invasive. Self-seeds prolifically. Consider containers. Bee magnet (Melissa = honey leaf). Medicinal: calming, antiviral, digestive aid. Best used fresh.',
        'icon': '🌿'
    },
    {
        'id': 'marjoram-1',
        'name': 'Marjoram (Sweet)',
        'scientificName': 'Origanum majorana',
        'category': 'herb',
        'spacing': 8,
        'rowSpacing': 12,
        'daysToMaturity': 70,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': ['tomato-1', 'pepper-bell-1', 'eggplant-1', 'bean-bush-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.5, 'max': 7.5},
        'plantingDepth': 0.125,
        'germinationTemp': {'min': 65, 'max': 70},
        'soil_temp_min': 65,
        'transplantWeeksBefore': 6,
        'germination_days': 10,
        'ideal_seasons': ['spring', 'summer'],
        'heat_tolerance': 'medium',
        'notes': 'Tender perennial (zones 9-10), annual elsewhere. Sweeter than oregano. Essential French/Italian herb. Excellent for containers - bring indoors in winter. Harvest before flowering. Dries well. Cut regularly for bushy growth.',
        'icon': '🌿'
    },
    {
        'id': 'tarragon-1',
        'name': 'Tarragon (French)',
        'scientificName': 'Artemisia dracunculus var. sativa',
        'category': 'herb',
        'spacing': 18,
        'rowSpacing': 24,
        'daysToMaturity': 60,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['eggplant-1', 'pepper-bell-1', 'tomato-1'],
        'incompatiblePlants': [],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.3, 'max': 7.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 4,
        'germination_days': 0,
        'ideal_seasons': ['spring', 'summer'],
        'heat_tolerance': 'medium',
        'notes': 'Perennial zones 4-8. French variety ONLY - sterile (no seeds). Propagate by division/cuttings. If seeds sold, they are inferior Russian tarragon. Classic French herb for béarnaise sauce. Anise flavor. Divide every 3-4 years. Freezes well.',
        'icon': '🌿'
    }
,    # ========== FRUIT TREES ==========
    {
        'id': 'apple-1',
        'name': 'Apple',
        'scientificName': 'Malus domestica',
        'category': 'fruit',
        'spacing': 240,
        'rowSpacing': 240,
        'daysToMaturity': 1825,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['nasturtium-1', 'chive-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 75},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'germination_days': 60,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'medium',
        'notes': 'Perennial tree zones 3-8. First harvest year 4-6 (dwarf), 5-8 (semi-dwarf), 6-10 (standard). Requires 800-1000 chill hours. Most varieties need cross-pollination - plant 2+ compatible varieties. Rootstocks: M27 dwarf (6-8ft), M26 semi-dwarf (12-15ft), MM111 standard (20-25ft). Productive 30-50 years. Prune annually in late winter. Space semi-dwarf 20ft.',
        'icon': '🍎'
    },
    {
        'id': 'pear-1',
        'name': 'Pear',
        'scientificName': 'Pyrus communis',
        'category': 'fruit',
        'spacing': 240,
        'rowSpacing': 240,
        'daysToMaturity': 1825,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['nasturtium-1', 'chive-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 75},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'germination_days': 60,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'medium',
        'notes': 'Perennial tree zones 4-8. First harvest year 4-7. Requires 600-900 chill hours. Needs cross-pollination - plant 2+ varieties. Fire blight susceptible - choose resistant varieties. Long-lived (50-75 years). Rootstocks: OHxF 87 semi-dwarf (12-18ft), Bartlett standard (20-25ft). More upright than apple. Harvest under-ripe, ripen indoors.',
        'icon': '🍐'
    },
    {
        'id': 'cherry-sweet-1',
        'name': 'Cherry (Sweet)',
        'scientificName': 'Prunus avium',
        'category': 'fruit',
        'spacing': 240,
        'rowSpacing': 240,
        'daysToMaturity': 1460,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['nasturtium-1', 'chive-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'germination_days': 90,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'medium',
        'notes': 'Perennial tree zones 5-8. First harvest year 4-7. Requires 700-900 chill hours. Most need cross-pollination - check variety compatibility charts. Birds LOVE cherries - netting essential. Rootstocks: Gisela 5 dwarf (8-10ft), Gisela 6 semi-dwarf (12-15ft), Mazzard standard (25-30ft). Productive 15-25 years. Spring frost risk to blossoms.',
        'icon': '🍒'
    },
    {
        'id': 'cherry-sour-1',
        'name': 'Cherry (Sour/Tart)',
        'scientificName': 'Prunus cerasus',
        'category': 'fruit',
        'spacing': 180,
        'rowSpacing': 180,
        'daysToMaturity': 1460,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['nasturtium-1', 'chive-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'germination_days': 90,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'medium',
        'notes': 'Perennial tree zones 4-8. First harvest year 3-5. Requires 1000-1200 chill hours. SELF-FERTILE - only need 1 tree. Hardier than sweet cherries. Smaller tree (12-15ft natural). Excellent for pies, preserves. Montmorency most popular variety. More disease resistant than sweet. Productive 20-30 years. Birds less interested than sweet.',
        'icon': '🍒'
    },
    {
        'id': 'plum-1',
        'name': 'Plum',
        'scientificName': 'Prunus domestica',
        'category': 'fruit',
        'spacing': 240,
        'rowSpacing': 240,
        'daysToMaturity': 1460,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': ['nasturtium-1', 'chive-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 6.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'germination_days': 90,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'medium',
        'notes': 'Perennial tree zones 4-9. First harvest year 3-6. European plums 700-1000 chill hours, Japanese 500-900. Some self-fertile (European), some need cross-pollination (Japanese). Rootstocks: Citation semi-dwarf (12-15ft), Myrobalan standard (20ft). Heavy bearer - thin fruit to prevent limb breakage. Excellent for fresh eating, drying (prunes). Productive 15-25 years.',
        'icon': '🍑'
    },
    {
        'id': 'peach-1',
        'name': 'Peach',
        'scientificName': 'Prunus persica',
        'category': 'fruit',
        'spacing': 200,
        'rowSpacing': 200,
        'daysToMaturity': 1095,
        'frostTolerance': 'semi-hardy',
        'winterHardy': True,
        'companionPlants': ['nasturtium-1', 'chive-1', 'basil-1'],
        'incompatiblePlants': ['potato-1', 'tomato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0,
        'germinationTemp': {'min': 65, 'max': 75},
        'soil_temp_min': 65,
        'transplantWeeksBefore': 0,
        'germination_days': 90,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'high',
        'notes': 'Perennial tree zones 5-9. First harvest year 2-4. Requires 600-900 chill hours. SELF-FERTILE - only need 1 tree. Short-lived (15-20 years) but productive. Rootstocks: Lovell semi-dwarf (12-15ft), natural 15-20ft. Peach leaf curl disease - spray copper in dormancy. Requires aggressive fruit thinning (6" apart). Heavy feeder. Genetic dwarf varieties for containers.',
        'icon': '🍑'
    },
    {
        'id': 'apricot-1',
        'name': 'Apricot',
        'scientificName': 'Prunus armeniaca',
        'category': 'fruit',
        'spacing': 200,
        'rowSpacing': 200,
        'daysToMaturity': 1095,
        'frostTolerance': 'semi-hardy',
        'winterHardy': True,
        'companionPlants': ['nasturtium-1', 'chive-1'],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'germination_days': 90,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'high',
        'notes': 'Perennial tree zones 4-9. First harvest year 3-4. Requires 600-900 chill hours. SELF-FERTILE - only need 1 tree. Blooms VERY early - spring frost risk high in cold climates. Excellent for drying, canning. Rootstocks: Citation semi-dwarf (12-15ft), natural 15-20ft. Drought-tolerant once established. Thin fruit to 4" apart. Productive 20-30 years. Birds love ripe fruit.',
        'icon': '🍑'
    },
    {
        'id': 'fig-1',
        'name': 'Fig',
        'scientificName': 'Ficus carica',
        'category': 'fruit',
        'spacing': 180,
        'rowSpacing': 180,
        'daysToMaturity': 730,
        'frostTolerance': 'tender',
        'winterHardy': False,
        'companionPlants': [],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 6.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 70, 'max': 85},
        'soil_temp_min': 70,
        'transplantWeeksBefore': 0,
        'germination_days': 30,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'high',
        'notes': 'Perennial tree/large shrub zones 7-10 (6 with protection). First harvest year 1-2 - FASTEST bearing fruit tree. Requires 100-300 chill hours. SELF-FERTILE. Common fig varieties need no pollination. Excellent for containers - bring indoors in winter. Brown Turkey, Chicago Hardy cold-hardy varieties. Can die back and regrow from roots. 2 crops/year in warm climates. Highly productive.',
        'icon': '🍇'
    },
    {
        'id': 'persimmon-1',
        'name': 'Persimmon (American)',
        'scientificName': 'Diospyros virginiana',
        'category': 'fruit',
        'spacing': 240,
        'rowSpacing': 240,
        'daysToMaturity': 1825,
        'frostTolerance': 'very-hardy',
        'winterHardy': True,
        'companionPlants': [],
        'incompatiblePlants': [],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 7.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'germination_days': 90,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'high',
        'notes': 'Perennial tree zones 4-9. First harvest year 4-6. American native - VERY cold hardy (to -25F). Dioecious - need male + female for fruit (or self-fertile varieties). Small fruit (1-2"), extremely high nutrition. Eat when fully soft/ripe (astringent when firm). Easy to grow, drought-tolerant, pest-free. Can reach 30-60ft. Asian persimmon (D. kaki) less hardy but larger fruit. Productive 50+ years.',
        'icon': '🍊'
    },
    # ========== NUT TREES ==========
    {
        'id': 'almond-1',
        'name': 'Almond',
        'scientificName': 'Prunus dulcis',
        'category': 'nut',
        'spacing': 240,
        'rowSpacing': 240,
        'daysToMaturity': 1825,
        'frostTolerance': 'semi-hardy',
        'winterHardy': True,
        'companionPlants': [],
        'incompatiblePlants': ['potato-1'],
        'waterNeeds': 'low',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 75},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'germination_days': 90,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'high',
        'notes': 'Perennial tree zones 5-9. First harvest year 5-6. Requires 200-400 chill hours. Needs cross-pollination - plant 2+ varieties. Blooms VERY early - spring frost kills crop in humid climates. Best in California/arid West. Rootstocks: Nemaguard semi-dwarf (15-20ft), Lovell standard (20-25ft). Drought-tolerant. Harvest when hulls split. Shell and dry nuts. Productive 25-30 years.',
        'icon': '🌰'
    },
    {
        'id': 'walnut-1',
        'name': 'Walnut (English/Black)',
        'scientificName': 'Juglans regia/nigra',
        'category': 'nut',
        'spacing': 480,
        'rowSpacing': 480,
        'daysToMaturity': 2555,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': [],
        'incompatiblePlants': ['tomato-1', 'potato-1', 'pepper-bell-1', 'apple-1'],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 75},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'germination_days': 120,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'medium',
        'notes': 'Perennial tree zones 4-9. First harvest year 6-10. English walnut (J. regia) requires 700-1000 chill hours, self-fertile. Black walnut (J. nigra) native, super hardy, smaller nuts. ALLELOPATHIC - juglone toxin kills tomatoes, apples, many plants. Needs deep soil. Massive tree (40-60ft). Harvest when hulls split, remove hulls immediately. Cure nuts 2-4 weeks. Productive 50-100+ years. Valuable timber tree.',
        'icon': '🌰'
    },
    {
        'id': 'pecan-1',
        'name': 'Pecan',
        'scientificName': 'Carya illinoinensis',
        'category': 'nut',
        'spacing': 480,
        'rowSpacing': 480,
        'daysToMaturity': 2555,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': [],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 6.0, 'max': 7.0},
        'plantingDepth': 0,
        'germinationTemp': {'min': 70, 'max': 85},
        'soil_temp_min': 70,
        'transplantWeeksBefore': 0,
        'germination_days': 90,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'high',
        'notes': 'Perennial tree zones 6-9. First harvest year 6-10. Requires 500-1000 chill hours. Needs cross-pollination - plant 2+ varieties with overlapping pollen shed. Long growing season required (200+ days). Deep taproot - needs deep soil. Massive tree (70-100ft), space 40ft apart. Northern varieties: Pawnee, Kanza. Southern: Desirable, Elliot. Alternate bearing (heavy crop every 2 years). Productive 50-100+ years.',
        'icon': '🌰'
    },
    {
        'id': 'hazelnut-1',
        'name': 'Hazelnut (Filbert)',
        'scientificName': 'Corylus avellana',
        'category': 'nut',
        'spacing': 180,
        'rowSpacing': 180,
        'daysToMaturity': 730,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': [],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 7.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 60, 'max': 70},
        'soil_temp_min': 60,
        'transplantWeeksBefore': 0,
        'germination_days': 90,
        'ideal_seasons': ['spring', 'fall'],
        'heat_tolerance': 'medium',
        'notes': 'Perennial shrub/small tree zones 4-9. First harvest year 2-5 - FAST for a nut. Requires 800-1200 chill hours. Needs cross-pollination - plant 2+ varieties. Multi-stemmed shrub (12-15ft), can train as tree. Eastern Filbert Blight resistant varieties essential in humid climates. Deer resistant. Harvest when husks turn brown. Dry nuts 2 weeks. Productive 40-50 years. Excellent for permaculture hedges.',
        'icon': '🌰'
    },
    {
        'id': 'chestnut-1',
        'name': 'Chestnut',
        'scientificName': 'Castanea mollissima',
        'category': 'nut',
        'spacing': 360,
        'rowSpacing': 360,
        'daysToMaturity': 1825,
        'frostTolerance': 'hardy',
        'winterHardy': True,
        'companionPlants': [],
        'incompatiblePlants': [],
        'waterNeeds': 'medium',
        'sunRequirement': 'full',
        'soilPH': {'min': 5.5, 'max': 6.5},
        'plantingDepth': 0,
        'germinationTemp': {'min': 65, 'max': 75},
        'soil_temp_min': 65,
        'transplantWeeksBefore': 0,
        'germination_days': 60,
        'ideal_seasons': ['spring'],
        'heat_tolerance': 'medium',
        'notes': 'Perennial tree zones 4-8. First harvest year 3-7. Chinese chestnut (C. mollissima) blight-resistant, American hybrids available. Requires 400-600 chill hours. Needs cross-pollination - plant 2+ trees. Large tree (40-60ft), space 30ft apart. Nuts fall in spiny burrs - wear gloves. High-quality carbohydrate crop, can substitute for grains. Roast, grind into flour, or eat fresh. Productive 50-100 years. Valuable homestead staple food.',
        'icon': '🌰'
    }

]

# Compost materials with C:N ratios
COMPOST_MATERIALS = {
    'grass-clippings': {'type': 'green', 'cnRatio': 20},
    'food-scraps': {'type': 'green', 'cnRatio': 15},
    'coffee-grounds': {'type': 'green', 'cnRatio': 20},
    'fresh-manure': {'type': 'green', 'cnRatio': 10},
    'chicken-manure': {'type': 'green', 'cnRatio': 12},
    'hay-fresh': {'type': 'green', 'cnRatio': 15},
    'garden-waste': {'type': 'green', 'cnRatio': 30},
    'dried-leaves': {'type': 'brown', 'cnRatio': 60},
    'straw': {'type': 'brown', 'cnRatio': 80},
    'wood-chips': {'type': 'brown', 'cnRatio': 400},
    'cardboard': {'type': 'brown', 'cnRatio': 350},
    'paper': {'type': 'brown', 'cnRatio': 175},
    'sawdust': {'type': 'brown', 'cnRatio': 500},
    'corn-stalks': {'type': 'brown', 'cnRatio': 60},
    'pine-needles': {'type': 'brown', 'cnRatio': 80}
}

def get_plant_by_id(plant_id):
    """Get plant details by ID"""
    for plant in PLANT_DATABASE:
        if plant['id'] == plant_id:
            return plant
    return None

def get_winter_hardy_plants():
    """Get all winter-hardy plants"""
    return [p for p in PLANT_DATABASE if p['winterHardy']]

def get_plants_by_category(category):
    """Get plants by category"""
    return [p for p in PLANT_DATABASE if p['category'] == category]

def get_companion_plants(plant_id):
    """Get recommended companion plants for a given plant"""
    plant = get_plant_by_id(plant_id)
    if not plant:
        return []

    companions = []
    for comp_id in plant.get('companionPlants', []):
        comp = get_plant_by_id(comp_id)
        if comp:
            companions.append(comp)
    return companions

def get_incompatible_plants(plant_id):
    """Get incompatible plants for a given plant"""
    plant = get_plant_by_id(plant_id)
    if not plant:
        return []

    incompatible = []
    for incomp_id in plant.get('incompatiblePlants', []):
        incomp = get_plant_by_id(incomp_id)
        if incomp:
            incompatible.append(incomp)
    return incompatible
