"""Add indexes to frequently queried FK columns

Revision ID: 631fced45d74
Revises: e2c4d6d3bc2f
Create Date: 2026-03-23 12:56:43.790476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631fced45d74'
down_revision = 'e2c4d6d3bc2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_bed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garden_bed_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('garden_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garden_plan_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('garden_plan_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garden_plan_item_garden_plan_id'), ['garden_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_garden_plan_item_plant_id'), ['plant_id'], unique=False)

    with op.batch_alter_table('indoor_seed_start', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indoor_seed_start_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('planted_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planted_item_garden_bed_id'), ['garden_bed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planted_item_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planted_item_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('planting_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planting_event_garden_bed_id'), ['garden_bed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planting_event_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planting_event_succession_group_id'), ['succession_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planting_event_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planting_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planting_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_planting_event_succession_group_id'))
        batch_op.drop_index(batch_op.f('ix_planting_event_plant_id'))
        batch_op.drop_index(batch_op.f('ix_planting_event_garden_bed_id'))

    with op.batch_alter_table('planted_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planted_item_user_id'))
        batch_op.drop_index(batch_op.f('ix_planted_item_plant_id'))
        batch_op.drop_index(batch_op.f('ix_planted_item_garden_bed_id'))

    with op.batch_alter_table('indoor_seed_start', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indoor_seed_start_user_id'))

    with op.batch_alter_table('garden_plan_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garden_plan_item_plant_id'))
        batch_op.drop_index(batch_op.f('ix_garden_plan_item_garden_plan_id'))

    with op.batch_alter_table('garden_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garden_plan_user_id'))

    with op.batch_alter_table('garden_bed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garden_bed_user_id'))

    # ### end Alembic commands ###
