"""Add source and indoor_seed_start_id to GardenPlanItem

Revision ID: b4d826b4780f
Revises: 579239b7ea80
Create Date: 2026-04-06 09:13:50.283476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d826b4780f'
down_revision = '579239b7ea80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_plan_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('indoor_seed_start_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_garden_plan_item_indoor_seed_start_id'), ['indoor_seed_start_id'], unique=False)
        batch_op.create_foreign_key('fk_garden_plan_item_indoor_seed_start', 'indoor_seed_start', ['indoor_seed_start_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_plan_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_garden_plan_item_indoor_seed_start', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_garden_plan_item_indoor_seed_start_id'))
        batch_op.drop_column('indoor_seed_start_id')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
