"""Add harvest_group_id to harvest_record

Revision ID: c79bda51a2e9
Revises: faa8053ea705
Create Date: 2026-05-05 07:33:35.959712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79bda51a2e9'
down_revision = 'faa8053ea705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvest_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harvest_group_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_harvest_record_harvest_group_id'), ['harvest_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvest_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harvest_record_harvest_group_id'))
        batch_op.drop_column('harvest_group_id')

    # ### end Alembic commands ###
