"""Add cancelled_at soft-delete to PlantedItem

Revision ID: f2bb35af831e
Revises: c79bda51a2e9
Create Date: 2026-05-13 08:14:54.259887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2bb35af831e'
down_revision = 'c79bda51a2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planted_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_planted_item_cancelled_at'), ['cancelled_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planted_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planted_item_cancelled_at'))
        batch_op.drop_column('cancelled_at')

    # ### end Alembic commands ###
