"""Add cancelled_at soft-delete to PlantingEvent and IndoorSeedStart

Revision ID: faa8053ea705
Revises: d37b8238c461
Create Date: 2026-04-21 12:36:46.519615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa8053ea705'
down_revision = 'd37b8238c461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indoor_seed_start', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_indoor_seed_start_cancelled_at'), ['cancelled_at'], unique=False)

    with op.batch_alter_table('planting_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_planting_event_cancelled_at'), ['cancelled_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planting_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planting_event_cancelled_at'))
        batch_op.drop_column('cancelled_at')

    with op.batch_alter_table('indoor_seed_start', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indoor_seed_start_cancelled_at'))
        batch_op.drop_column('cancelled_at')

    # ### end Alembic commands ###
